#!/bin/bash

if [ "$#" -ne 3 ]; then
  echo "Użycie: $0 mapa.txt input.csv output.csv"
  exit 1
fi

MAPA="$1"
INPUT="$2"
OUTPUT="$3"

SED_SCRIPT=$(mktemp)

while IFS='|' read -r OLD NEW
do
  [ -z "$OLD" ] && continue

  OLD_ESC=$(printf '%s\n' "$OLD" | sed 's/[\/&]/\\&/g')
  NEW_ESC=$(printf '%s\n' "$NEW" | sed 's/[\/&]/\\&/g')

  echo "s/$OLD_ESC/$NEW_ESC/g" >> "$SED_SCRIPT"

done < "$MAPA"

sed -f "$SED_SCRIPT" "$INPUT" > "$OUTPUT"

rm "$SED_SCRIPT"

echo "Gotowe → $OUTPUT"
